cli: Fix -c and -P on python3.
Fixes:

    Traceback (most recent call last):
      File "/usr/local/bin/pstore", line 871, in <module>
        main(sys.argv)
      File "/usr/local/bin/pstore", line 861, in main
        pstore(args)
      File "/usr/local/bin/pstore", line 856, in pstore
        run_command(command or 'default', args, config)
      File "/usr/local/bin/pstore", line 454, in run_command
        pstore.add_machine(name, new_password, [config['user']] + allow)
      File "/usr/local/bin/pstore", line 73, in add_machine
        fp = BytesIO(new_password)
    TypeError: a bytes-like object is required, not 'str'